name = "SpinWeightedSpheroidalHarmonics"
uuid = "680e17a6-2a17-48fd-ae01-e2b5a643bef0"
authors = ["Rico Ka Lok Lo"]
version = "0.2.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[compat]
AbstractTrees = "0.4.2"
QuadGK = "2.4.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
